"""
Agent State Module for Agentic RAG

Tracks state variables across the state-machine execution loop:
- Query history and intent classification
- Retrieved context and relevance evaluations
- Rewrite counts and web search fallback flags
- Step-by-step reasoning thought logs for UI streaming
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional


@dataclass
class AgentThought:
    """Represents a single step-by-step reasoning thought generated by the agent."""
    step: str
    thought: str
    status: str = "info"  # "info", "warning", "success", "error"
    timestamp: float = 0.0


@dataclass
class AgentState:
    """
    Main state container for the Agentic RAG execution loop.
    Passed between node functions in the State Machine.
    """
    original_query: str
    current_query: str = ""
    intent: str = "document_qa"  # "chitchat", "document_qa", "web_search"
    retrieved_chunks: List[Dict[str, Any]] = field(default_factory=list)
    relevance_grade: str = "UNKNOWN"  # "HIGH", "MEDIUM", "LOW"
    retry_count: int = 0
    max_retries: int = 2
    used_web_search: bool = False
    web_results: List[Dict[str, Any]] = field(default_factory=list)
    final_answer: str = ""
    groundedness_grade: str = "UNKNOWN"  # "GROUNDED", "NOT_GROUNDED", "SKIPPED"
    thoughts: List[Dict[str, Any]] = field(default_factory=list)
    
    def __post_init__(self):
        if not self.current_query:
            self.current_query = self.original_query

    def add_thought(self, step: str, thought: str, status: str = "info") -> Dict[str, Any]:
        """Record an agent thought step for UI reporting/streaming."""
        thought_dict = {
            "step": step,
            "thought": thought,
            "status": status
        }
        self.thoughts.append(thought_dict)
        return thought_dict
